### ISSUE TITLE
Prettify Slack Alert

### ISSUE THREAD

**Issue by SteveKekacs** [underdog-tech/vulnbot#46]
# 🚀 Feature Request

## Is your feature request related to a problem? Please describe.
The current slack alerts are a bit hard to read. It's a lot of text, not much spacing, etc. It makes it hard to easily look at/generally looks a little "jank".

## Describe the solution you'd like
A prettified slack alert using the [slack block kit](https://api.slack.com/block-kit).

**Comment by tarkatronic** [comment]
@SteveKekacs Thanks for the request! I absolutely agree. I think the big question is going to be, what should it look like? I haven't really looked into the block kit yet, so I definitely want to do a deep dive on that.

And of course, any contributions are welcome!

**Comment by tarkatronic** [comment]
I've started working on this, but wanted to note a couple of changes on approach.
1. I am attempting to use the icon/severity detection proposed, but instead of the "circle" icons used above, I'm going to use the pre-existing icon configuration. That way a user can decide what Slack icons to use.
2. The repositories are currently sorted alphabetically, and I'm going to keep it that way for now. That's a fairly easy way to do it for now, and I think if we want to change that sorting algorithm that can be another future enhancement.

I also just thought of an interesting minor thing that puts a bump in the formatting above: What if one of the severities has double or triple digit numbers of vulnerabilities? Hopefully that isn't the case, but... what if? I think I'm going to just pad the numbers into a 3-character wide space. That will allow up to 999 in one severity column without throwing things out of alignment. Ideally 2 characters would be fine, but I could see the summary column easily growing larger.

**Comment by tarkatronic** [comment]
After a bit of fiddling, I'm going with this for the summary report! Also, I'm going to move the date/time to a context for the team reports like I did here. That's just slick.
<img width="451" alt="Screenshot 2023-05-23 at 12 15 42 PM" src="https://github.com/underdog-tech/vulnbot/assets/37809/36141871-33a7-438d-9c1c-9f102807ca4f">
